// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/9/2026, 4:42:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/dhan/Applications/AI-Automated_Payment-Reminder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/plugins/**/*.{js,ts,mjs}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/composables/**/*.{js,ts,mjs}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/utils/**/*.{js,ts,mjs}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/dhan/Applications/AI-Automated_Payment-Reminder/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;